### ISSUE TITLE
Bring back bash_profile-mods.bash (and add zsh profile mods!)

### ISSUE THREAD

**Issue by jrfoell** [salcode/salcode-git#10]
Would love to see those things added back to this (new) repo!

**Comment by salcode** [comment]
Thank you for your interest in this repo and the now archived [ironcodestudio/ironcode-git-enhancements](https://github.com/ironcodestudio/ironcode-git-enhancements).

I think for me the shell aliases and functions are out of scope for _this_ repo.

I also think [these lines in my zsh configuration](https://github.com/salcode/salcode-zsh/blob/21c10babbf1aef9ad70c20ff6944cf5da93a7e84/zshrc#L26-L53) and the blog post [Add git status to zsh prompt](https://salferrarello.com/zsh-git-status-prompt/) cover the same functionality for zsh (and as I'm no longer using bash, I don't want to take on the task of maintaining anything for bash specifically - sorry).

If there is any functionality that you were using that was in the `bash_profile-mods.bash` that isn't covered by these two resources, please let me know because I'd at least like to make a note of it (and maybe even add it in [salcode/salcode-zsh](https://github.com/salcode/salcode-zsh)).

I do realize this isn't as convenient as including a file like `bash_profile-mods.bash` (and I could imagine creating a separate repo to create a zsh file specifically for adding this Git stuff, but I don't foresee going down that path).

Thanks for bringing this idea up and making me put a little more thought into it.

**Comment by salcode** [comment]
After taking some time to think about this, I'm still of the same opinion I mentioned in my original comment.

> I think for me the shell aliases and functions are out of scope for _this_ repo.

I've tagged this as `wontfix` and I'm closing this issue.
